extension_dir = "C:\Users\Asus\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.2_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"

extension=php_openssl.dll
extension=php_pdo_mysql.dll
extension=php_mysqli.dll
extension=php_mbstring.dll
extension=php_fileinfo.dll
extension=php_curl.dll
extension=php_gd.dll
extension=php_intl.dll
extension=php_zip.dll
extension=php_pdo_sqlite.dll
extension=php_sqlite3.dll
